swagger: "2.0"
info:
  title: "E-commerce Recommendation API"
  version: "1.0"
paths:
  /predict:
    post:
      summary: "Invoke SageMaker model for product recommendation"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "payload"
          description: "CSV formatted input data"
          required: true
          schema:
            type: "object"
            properties:
              payload:
                type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            properties:
              prediction:
                type: "string"
